// frontend/src/lib/components/utility/Loading.svelte
<script lang="ts">
    import { faFish } from "@fortawesome/free-solid-svg-icons/faFish";
    import FaIcon from "./FaIcon.svelte";
</script>

<div class="flex flex-col items-center text-gray-700">
    <!--Let's take this fish out for a swimming -->
    <FaIcon icon={faFish} class="animate-swim" size="75px" />
    <span class="text-2xl">
        <slot />
    </span>
</div>

// frontend/components/Loading.tsx
import { FunctionComponent } from "react";
import PageCard from "./PageCard";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFish } from "@fortawesome/free-solid-svg-icons";

export interface LoadingProps {
  message: string;
}

const Loading: FunctionComponent<LoadingProps> = (props) => {
  return (
    <div className="flex flex-col items-center">
      {/* Let's take this fish out for a swimming */}
      <FontAwesomeIcon icon={faFish} size="3x" color="gray" className="animate-swim" />
      <span className="text-2xl">{props.message}</span>
    </div>
  );
};

export default Loading;
