// frontend/src/routes/decks.svelte
<script lang="ts">
  import { getDecks } from "../lib/api";
  import Deck from "../lib/components/Deck.svelte";
  import RoundButton from "../lib/components/inputs/buttons/RoundButton.svelte";
  import Page from "../lib/components/Page.svelte";
  import Loading from "../lib/components/utility/Loading.svelte";
</script>

<svelte:head>
  <title>Ebisu - Decks</title>
</svelte:head>

<Page>
  <!-- Breadcrumb slot -->
  <div slot="breadcrumbs" class="breadcrumbs">
    <span>DECKS</span>
  </div>

  <!-- Button slot -->
  <div slot="buttons" class="flex gap-4">
    <RoundButton href="/deck/new" color="indigo">New deck</RoundButton>
    <RoundButton href="/logout" color="red">Logout</RoundButton>
  </div>
  <!-- Main content -->
  <main class="flex-grow flex">
    {#await getDecks()}
      <div class="flex-grow flex flex-col justify-center">
        <Loading>Loading decks</Loading>
      </div>
    {:then decks}
      <div class="flex-grow grid items-stretch lg:grid-cols-4 md:grid-cols-2 sm:grid-cols-1 auto-rows-max gap-8 p-8">
        {#each decks as deck}
          <Deck deck={deck} />
        {/each}
      </div>
    {/await}
  </main>
</Page>

// frontend/pages/decks.tsx
import Deck from "../components/Deck";
import { DeckModel } from "../lib/models/deck";
import { useEffect, useState } from "react";
import { NextPage } from "next";
import PageCard, { Breadcrumb } from "../components/PageCard";
import LinkButton from "../components/inputs/buttons/LinkButton";
import Loading from "../components/Loading";
import { getDecks } from "../lib/api";

function renderLoading() {
  return (
    <div className="flex-grow flex flex-col justify-center">
      <Loading message="Loading decks..." />
    </div>
  );
}

function renderDecks(decks: DeckModel[]) {
  return (
    <main className="flex-grow grid items-stretch lg:grid-cols-4 md:grid-cols-2 sm:grid-cols-1 auto-rows-max gap-8 p-8 bg-white">
      {decks.map((deck) => (
        <Deck key={deck.id} deck={deck} />
      ))}
    </main>
  );
}

const DecksPage: NextPage = () => {
  useEffect(() => {
    document.querySelector("body")?.classList.add("bg-indigo-200");
  });

  const [decks, setDecks] = useState<DeckModel[] | null>(null);
  useEffect(() => {
    if (decks === null) {
      getDecks().then(setDecks);
    }
  }, [decks]);

  const buttons = [
    <LinkButton color="green" title="New Deck" href="/deck/new" />,
    <LinkButton color="red" title="Logout" href="/logout" />,
  ];

  const breadcrumbs: Breadcrumb[] = [{ name: "DECKS" }];

  return (
    <PageCard className="flex-grow flex flex-col bg-white" headerButtons={buttons} breadcrumbs={breadcrumbs}>
      {decks === null ? renderLoading() : renderDecks(decks)}
    </PageCard>
  );
};

export default DecksPage;
