// frontend/src/routes/deck/[id]/study.svelte
<script context="module" lang="ts">
    import { getDeck } from "../../../lib/api";

    export async function load({ page }) {
        const { id } = page.params;
        const deck = await getDeck(id);

        return {
            props: {
                deck
            }
        };
    }
</script>

<script lang="ts">
    import Page from "../../../lib/components/Page.svelte";
    import Loading from "../../../lib/components/utility/Loading.svelte";
    import { getNextCard } from "../../../lib/api";
    import type { DeckModel } from "../../../lib/models/deck";

    export let deck: DeckModel;
    let hidden = true;

    let card = getNextCard(deck?.id, null);

    function handleAnswer(remembered: boolean): void {
        hidden = true;
        card = getNextCard("0", "0");
    }
</script>

<Page>
    <!-- Breadcrumbs content -->
    <div slot="breadcrumbs" class="breadcrumbs">
        <a class="underline text-gray-600" href="/decks">DECKS</a>
        <span>&gt;</span>
        <span>{deck.name}</span>
    </div>
    <!-- Main content -->
    <main class="flex-grow flex flex-col md:justify-center text-center items-stretch w-full">
        {#await card}
            <Loading>Loading next card</Loading>
        {:then card}
            <div class="flex-grow flex flex-col items-center">
                <div class="flex-grow flex flex-col justify-center pb-4 px-4 md:px-12">
                    <span class="block text-2xl">{card.question.content.toString()}</span>
                </div>
                <div class="flex-grow flex flex-col justify-center px-4 md:px-12 transition-opacity"
                     class:hidden={hidden}>
                    <span class="block text-2xl">{card.answer.content.toString()}</span>
                </div>
            </div>

            {#if hidden}
                <button on:click={() => hidden = false}
                        class="leading-10 font-medium text-gray-800 bg-green-300 hover:bg-green-400 transition-colors w-full">
                    SHOW ANSWER
                </button>
            {:else}
                <div class="flex">
                    <button on:click={() => handleAnswer(true)}
                            class="leading-10 font-medium text-gray-800 bg-green-300 hover:bg-green-400 transition-colors w-1/2">
                        REMEMBERED
                    </button>
                    <button on:click={() => handleAnswer(false)}
                            class="leading-10 font-medium text-gray-800 bg-red-300 hover:bg-red-400 transition-colors w-1/2">
                        FORGOT
                    </button>
                </div>
            {/if}
        {/await}
    </main>
</Page>

// frontend/pages/deck/[id]/study.tsx
import { NextPage } from "next";
import { useEffect, useState } from "react";
import { CardModel, DeckModel } from "../../../lib/models/deck";
import PageCard, { Breadcrumb } from "../../../components/PageCard";
import { getNextCard } from "../../../lib/api";
import Loading from "../../../components/Loading";

export interface StudyProps {
  deck: DeckModel;
}

enum CardState {
  UNINITIALIZED,
  LOADING,
  HIDDEN,
  REVEALED,
  ANSWERED_OK,
  ANSWERED_NOK,
}

/**
 * Function responsible rendering the inner loading screen
 */
const renderLoading = () => {
  return <Loading message="Loading next card..." />;
};

/**
 * Function responsible rendering the current card
 */
const renderCard = (card: CardModel, state: CardState, setState: (state: CardState) => void) => {
  /**
   * Inner function responsible for rendering the buttons, depending on the current state
   */
  const renderButtons = () => {
    switch (state) {
      case CardState.HIDDEN:
        return (
          <button
            className="leading-10 font-bold bg-green-300 hover:bg-green-400 transition-colors w-full"
            onClick={() => setState(CardState.REVEALED)}
          >
            SHOW ANSWER
          </button>
        );
      case CardState.REVEALED:
        return (
          <>
            <button
              key="answer-ok"
              className="leading-10 font-bold bg-green-300 hover:bg-green-400 transition-colors w-1/2"
              onClick={() => setState(CardState.ANSWERED_OK)}
            >
              REMEMBERED
            </button>
            <button
              key="answer-nok"
              className="leading-10 font-bold bg-red-300 hover:bg-red-400 transition-colors w-1/2"
              onClick={() => setState(CardState.ANSWERED_NOK)}
            >
              FORGOT
            </button>
          </>
        );
      default:
        return null;
    }
  };

  return (
    <main className="flex-grow flex flex-col md:justify-center text-center items-stretch w-full">
      <div className="flex-grow flex flex-col p-6">
        <div className="flex gap-x-4 justify-center">
          {card.answer.tags.map((tag) => (
            <span className="border border-gray-500 bg-gray-100 rounded p-2">{tag}</span>
          ))}
        </div>
        <div className="flex-grow flex flex-col justify-center">
          <span className="text-4xl">{card.question.content}</span>
        </div>
        <hr className="border-dashed border-gray-500 mx-4 my-6" />
        <div className="flex gap-x-4 justify-center">
          {card.question.tags.map((tag) => (
            <span className="border border-gray-500 bg-gray-100 rounded p-2">{tag}</span>
          ))}
        </div>
        <div className="flex-grow flex flex-col justify-center gap-y-4">
          <span className={`transition-opacity text-4xl ${state === CardState.HIDDEN ? "opacity-0" : ""}`}>
            {card.answer.content}
          </span>
        </div>
      </div>

      <div className="flex">{renderButtons()}</div>
    </main>
  );
};

const StudyDeckPage: NextPage<StudyProps> = (props) => {
  const breadcrumbs: Breadcrumb[] = [{ name: "DECKS", href: "/decks" }, { name: props.deck?.name || "TEST DECK" }];

  useEffect(() => {
    document.querySelector("body")?.classList.add("bg-indigo-200");
  });

  const [card, setCard] = useState<CardModel | null>(null);
  const [state, setState] = useState(CardState.UNINITIALIZED);

  useEffect(() => {
    switch (state) {
      case CardState.ANSWERED_OK:
      case CardState.ANSWERED_NOK:
      case CardState.UNINITIALIZED:
        setState(CardState.LOADING);
        getNextCard().then((c) => {
          setState(CardState.HIDDEN);
          setCard(c);
        });
        return;
    }
  }, [state]);

  return (
    <PageCard className="flex-grow flex flex-col bg-white" breadcrumbs={breadcrumbs}>
      <div className="flex-grow flex flex-col sm:items-stretch md:items-center justify-center">
        {state === CardState.LOADING ? renderLoading() : card === null ? null : renderCard(card, state, setState)}
      </div>
    </PageCard>
  );
};

export default StudyDeckPage;
